export const api = window.axios.create({
  timeout: 10000,
});

export const LOG_LEVELS = {
  DEBUG: 10,
  INFO: 20,
  WARNING: 30,
  ERROR: 40,
  CRITICAL: 50,
};

export const DEFAULT_CONFIG = {
  username: "",
  password: "",
  use_global_credentials: true,
  auth_url: "",
  active_task: "",
  carrier: "无",
  carrier_custom: "",
  check_interval_minutes: 5,
  auto_start: false,
  headless: true,
  browser_timeout: 8000,
  login_timeout: 120,
  browser_user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
  browser_low_resource_mode: true,
  browser_disable_web_security: false,
  browser_extra_headers_json: "",
  browser_args: "--disable-blink-features=AutomationControlled\n--disable-software-rasterizer\n--disable-extensions\n--disable-background-timer-throttling\n--disable-backgrounding-occluded-windows\n--disable-renderer-backgrounding\n--disable-features=TranslateUI,BlinkGenPropertyTrees\n--disable-ipc-flooding-protection\n--disable-hang-monitor\n--disable-popup-blocking",
  stealth_mode: false,
  pause_enabled: true,
  pause_start_hour: 0,
  pause_end_hour: 6,
  network_targets: "8.8.8.8:53,114.114.114.114:53,www.baidu.com:443",
  network_strict_mode: true,
  backend_log_level: "INFO",
  frontend_log_level: "INFO",
  access_log: false,
  minimize_to_tray: true,
  auto_open_browser: false,
  login_then_exit: false,
  log_retention_days: 7,
  screenshot_retention_days: 7,
  custom_variables: {},
  proxy: "",
};

export const SETTINGS_TABS = [
  { id: 'account', label: '账号设置', hint: '账号、密码与认证地址' },
  { id: 'system', label: '系统设置', hint: '监控、日志与行为控制' },
  { id: 'browser', label: '浏览器设置', hint: '请求头、图片与浏览器参数' },
  { id: 'tasks', label: '任务设置', hint: '活动任务与模板入口' },
];

export const DEFAULT_PROFILE_SETTINGS = {
  name: '',
  match_gateway_ip: '',
  match_ssid: '',
  username: '',
  password: '',
  use_global_credentials: true,
  use_global_advanced: true,
  use_global_auth_url: true,
  use_global_task: true,
  auth_url: '',
  active_task: '',
  carrier: '无',
  carrier_custom: '',
  check_interval_minutes: 5,
  auto_start: false,
  headless: true,
  browser_timeout: 8000,
  login_timeout: 120,
  browser_user_agent: '',
  browser_low_resource_mode: true,
  browser_disable_web_security: false,
  browser_extra_headers_json: '',
  browser_args: "--disable-blink-features=AutomationControlled\n--disable-software-rasterizer\n--disable-extensions\n--disable-background-timer-throttling\n--disable-backgrounding-occluded-windows\n--disable-renderer-backgrounding\n--disable-features=TranslateUI,BlinkGenPropertyTrees\n--disable-ipc-flooding-protection\n--disable-hang-monitor\n--disable-popup-blocking",
  stealth_mode: false,
  pause_enabled: true,
  pause_start_hour: 0,
  pause_end_hour: 6,
  network_targets: '8.8.8.8:53,114.114.114.114:53,www.baidu.com:443',
  network_strict_mode: true,
  custom_variables: {},
};
